import zdgram

class Sticker:
    file_id: str
    file_unique_id: str
    type: str
    width: int
    height: int
    is_animated: bool
    is_video: bool
    thumbnail: "zdgram.types.PhotoSize"
    thumb: "zdgram.types.PhotoSize"
    emoji: str
    set_name: str
    premium_animation: None
    mask_position: None
    custom_emoji_id: str
    needs_repainting: bool
    file_size: int